unique_ids:
  forms:
    Form1: 6WLC4ZYUOQMQYBY6VZPLJOR5MSCCEW6A
  modules: {}
  server_modules: {}
  assets:
    theme.css: KCK7OIHGQWM4Q2WNVBWMNUYEWFXCJXTQ
    standard-page.html: RT2VLI3S62DLLNXGAHRQUEHAXM7EX7M2
  scripts: {}
